wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.4
    start_time: 1678752352.729213
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.4
      5: 0.13.11
      8:
      - 1
      - 2
      - 5
embedding_dim:
  desc: null
  value: 50
epochs:
  desc: null
  value: 10
hidden_dims:
  desc: null
  value:
  - 100
  - 20
  - 10
vocab_size:
  desc: null
  value: 10002
