dataset_1_RecurrentSiameseNet_both:
  batch_size: 64
  dropout: 0.1
  hidden_dim: 256
  lr: 0.0001
  n_steps: 6000
dataset_1_RecurrentSiameseNet_semantic:
  batch_size: 64
  dropout: 0.3
  hidden_dim: 128
  lr: 0.0001
  n_steps: 4000
dataset_1_RecurrentSiameseNet_syntactic:
  batch_size: 32
  dropout: 0.3
  hidden_dim: 32
  lr: 0.001
  n_steps: 8000
dataset_1_SiameseNet_both:
  batch_size: 64
  dropout: 0.1
  hidden_dim: 256
  lr: 0.0001
  n_steps: 6000
dataset_1_SiameseNet_semantic:
  batch_size: 16
  dropout: 0.1
  hidden_dim: 64
  lr: 0.001
  n_steps: 4000
dataset_1_SiameseNet_syntactic:
  batch_size: 32
  dropout: 0.2
  hidden_dim: 128
  lr: 0.001
  n_steps: 8000
dataset_2_RecurrentSiameseNet_both:
  batch_size: 64
  dropout: 0.3
  hidden_dim: 32
  lr: 0.001
  n_steps: 4000
dataset_2_RecurrentSiameseNet_semantic:
  batch_size: 64
  dropout: 0.3
  hidden_dim: 32
  lr: 0.0001
  n_steps: 6000
dataset_2_RecurrentSiameseNet_syntactic:
  batch_size: 32
  dropout: 0.2
  hidden_dim: 128
  lr: 0.0001
  n_steps: 8000
dataset_2_SiameseNet_both:
  batch_size: 32
  dropout: 0.2
  hidden_dim: 128
  lr: 0.001
  n_steps: 6000
dataset_2_SiameseNet_semantic:
  batch_size: 16
  dropout: 0.2
  hidden_dim: 64
  lr: 0.001
  n_steps: 8000
dataset_2_SiameseNet_syntactic:
  batch_size: 32
  dropout: 0.1
  hidden_dim: 128
  lr: 0.001
  n_steps: 8000
dataset_3_RecurrentSiameseNet_both:
  batch_size: 32
  dropout: 0.1
  hidden_dim: 128
  lr: 0.0001
  n_steps: 4000
dataset_3_RecurrentSiameseNet_semantic:
  batch_size: 16
  dropout: 0.2
  hidden_dim: 32
  lr: 0.001
  n_steps: 2000
dataset_3_RecurrentSiameseNet_syntactic:
  batch_size: 16
  dropout: 0.2
  hidden_dim: 256
  lr: 0.0001
  n_steps: 8000
dataset_3_SiameseNet_both:
  batch_size: 64
  dropout: 0.1
  hidden_dim: 64
  lr: 0.001
  n_steps: 4000
dataset_3_SiameseNet_semantic:
  batch_size: 64
  dropout: 0.3
  hidden_dim: 128
  lr: 0.001
  n_steps: 4000
dataset_3_SiameseNet_syntactic:
  batch_size: 32
  dropout: 0.2
  hidden_dim: 256
  lr: 0.0001
  n_steps: 6000
