dataset_1:
  syntactic:
    siamese:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
    recurrent:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
  semantic:
    siamese:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
    recurrent:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
dataset_2:
  syntactic:
    siamese:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
    recurrent:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
  semantic:
    siamese:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
    recurrent:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
dataset_3:
  syntactic:
    siamese:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
    recurrent:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
  semantic:
    siamese:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2
    recurrent:
      lr: 0.0001
      batch_size: 32
      n_steps: 2000
      hidden_dim: 64
      dropout: 0.2

